snip = {
    "Copertura al 100%": "Negli ultimi 8 anni circa siamo riusciti ad ottenere la copertura totale delle borse. Anche quest'anno, come Alter.POLIS, CollettivaMente e Studenti Indipendenti, abbiamo chiesto garanzie alla Regione ed a parole ci è stato detto che l'intenzione è la copertura al 100%. La reale situazione sarà nota solo verso dicembre, con il numero di richieste e lo stanziamento effettivo dei fondi. Come sempre vigileremo sull'operato della Regione",
    "Differenza tra standard e conferma": "Se l'anno passato hai ricevuto i benefici (posto letto e/o borsa), con la domanda di conferma ottieni sicuramente i benefici per cui fai richiesta (e che avevi già ricevuto). Hai la precedenza rispetto alla domanda standard.\nPuoi fare domanda di conferma solo se hai il numero di crediti richiesto (per questo si chiama \"per merito\")",
    "Rinuncia al posto letto dopo le graduatorie definitive": "La rinuncia al posto letto successivamente alle graduatorie definitive può comportare la perdita della borsa di studio da fuori sede completa. Per maggiori dettagli leggi a pagina 23 del bando.\n\nIn sintesi, se rifiuti poiché assegnatariз nelle graduatorie definitive di servizio abitativo o negli esiti della dichiarazione di interesse, diventi in sede (ai fini dell'importo della borsa).\n\nPer tutti gli altri casi, ti rimando alla pagina 23.",
    "CFU necessari durante l'anno per gli anni successivi": "La borsa EDISU è destinata a coloro che rispettano i requisiti economici (cioè ISEE e ISP sotto una certa soglia) e i requisiti di merito (devono aver totalizzato un tot di CFU negli anni precedenti).\n\nPer i primi anni non è naturalmente possibile valutare il merito essendo che lo studente non ha ancora sostenuto esami. Per cui lo studente deve ottenere 20 CFU entro il 10 agosto successivo per poter ottenere la seconda rata della borsa (o 20 CFU entro Novembre per non dover restituire la prima rata).\n\nQuesto discorso non si applica per gli anni successivi poichè per questi è possibile valutare il merito basandosi sugli anni precedenti. Per cui se al momento di fare domanda per anni successivi hai i CFU richiesti, risultando assegnatario hai diritto ad entrambe le rate della borsa.",
    "Elenco corsi STEM" : "https://www.edisu.piemonte.it/sites/default/files/risorse/bandi/2022/ELENCO%20CORSI%20STEM.pdf",
    "Dichiarazione di domicilio a titolo oneroso" : "La dichiarazione di domicilio a titolo oneroso va fatta da tutti lз studentз fuori che non sono ospiti delle residenze EDISU e non abbiano accettato (o dichiarato l'interesse) mediante Opzione Einaudi.\nServe per confermare lo status di fuori sede e va fatta tra il 28 Ottobre e il 5 Dicembre ore 12.00\n\nIl contratto da caricare deve avere le caratteristiche indicate all'articolo 8 del bando.",
    "Procedura di rifiuto": "Procedura di rifiuto:\n\nSe rifiuti via mail o senza fare il check in ottieni l'importo da \"studente in sede\" invece di quello da \"fuorisede con supporto abitativo\"\nSe rifiuti facendo check in e poi check out (cosa che si può fare nello stesso giorno) ottieni l'importo da \"studente pendolare\" invece di quello da \"fuorisede con supporto abitativo\"\n\nPer gli scambi mi raccomando di non PROPORRE né ACCETTARE scambi con dietro pagamenti in denaro od altra forma, sono ILLEGALI e possono farvi espellere da EDISU e rischiate una denuncia alla polizia postale, oltre che essere moralmente sbagliati e controproducenti visto che portano a meno scambi disponibili e a ledere il diritto allo studio universitario.",
    "Aggiornamento tariffe delle mense": "Sulle tariffe mense:\n\nSì, il CdA del 19 ha approvato le tariffe ristorazione aumentate, ma le decisioni del CdA devono ricevere il parere del Co.Re.Co. e dell'ARDSU.\n\nQuesti pareri sono obbligatori prima di mettere in effetto la misura e non sono ancora stati espressi, per cui non possono aumentare i prezzi.\n\nFinché non verrà dato un parere e non verranno poi date le giustificazioni da parte del CdA, allora si continuerà con la tariffa normale"

}